imports:
  - { resource: config.yml }

doctrine:
  dbal:
    dbname: supla_test

framework:
  profiler:
    collect: false
  session:
    storage_id: session.storage.mock_file
  test: ~

monolog:
  handlers:
    main:
      action_level: notice
    main_logger:
      max_files: 1
    autodiscover:
      level: debug
      max_files: 1

services:
  SuplaBundle\Tests\Integration\TestMailer: ~
  SuplaBundle\Mailer\SuplaMailer:
    $router: '@router'
    $templating: '@templating.engine.twig'
    $mailer: '@SuplaBundle\Tests\Integration\TestMailer'
    $mailerFrom: "%mailer_from%"
    $adminEmail: "%admin_email%"
    $defaultLocale: "%locale%"
    $localSuplaCloud: '@SuplaBundle\Model\LocalSuplaCloud'
  SuplaBundle\Model\TimeProvider:
    class: SuplaBundle\Tests\Integration\Traits\TestTimeProvider
  SuplaBundle\Supla\SuplaServer: '@SuplaBundle\Supla\SuplaServerMock'
  SuplaBundle\Supla\SuplaAutodiscover: '@SuplaBundle\Supla\SuplaAutodiscoverMock'
  SuplaBundle\Supla\SuplaServerMockCommandsCollector:
    public: false
    tags: [{name: data_collector, template: '@Supla/Supla/supla-server-mock-data-collector.html.twig', id: 'supla.supla_server_mock_data_collector'}]
  test.client:
    class: SuplaBundle\Tests\Integration\TestClient
    shared: false
    arguments:
      - '@kernel'
      - '%test.client.parameters%'
      - '@test.client.history'
      - '@test.client.cookiejar'

supla:
  brute_force_auth_prevention:
    enabled: true

swiftmailer:
  disable_delivery: true

web_profiler:
  toolbar: false
  intercept_redirects: false
