imports:
  - { resource: config.yml }

framework:
  profiler:
    only_exceptions: true
  router:
    resource: "%kernel.root_dir%/config/routing_dev.yml"
    strict_requirements: true

monolog:
  handlers:
    main:
      action_level: notice
    main_logger:
      max_files: 2
    autodiscover:
      level: debug
      max_files: 2

parameters:
  supla_protocol: http
  use_webpack_dev_server: true

services:
  SuplaBundle\Supla\SuplaServer: '@SuplaBundle\Supla\SuplaServerMock'
  SuplaBundle\Supla\SuplaAutodiscover: '@SuplaBundle\Supla\SuplaAutodiscoverMock'
  SuplaBundle\Supla\SuplaServerMockCommandsCollector:
    public: false
    tags: [{name: data_collector, template: '@Supla/Supla/supla-server-mock-data-collector.html.twig', id: 'supla.supla_server_mock_data_collector'}]

#swiftmailer:
#  delivery_addresses: ['%admin_email%']

web_profiler:
  intercept_redirects: false
  toolbar: true
